# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [16]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""],
    "Notes": ["", None, "active", None, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score   Notes
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None    None
2  Charlie      35     2022/03/01  88.0  active
3    David     NaN           None  92.5    None
4     None      40  April 5, 2022

### 🧯 2. Detecting Missing or Broken Values

In [17]:
df.isnull()

    Name    Age  Signup Date  Score  Notes
0  False  False        False  False  False
1  False  False        False   True   True
2  False  False        False  False  False
3  False   True         True  False   True
4   True  False        False  False  False

In [18]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
Notes          2
dtype: int64

In [19]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score Notes
1    Bob  thirty     not a date  None  None
3  David     NaN           None  92.5  None
4   None      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [20]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0,
    "Notes": "N/A"
})

      Name     Age    Signup Date Score   Notes
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0     N/A
2  Charlie      35     2022/03/01  88.0  active
3    David      -1     1970-01-01  92.5     N/A
4  Unknown      40  April 5, 2022

In [21]:
df.dropna()

      Name Age Signup Date Score   Notes
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0  active

### 🧬 4. Data Type Fixes

In [22]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
Notes          object
dtype: object

In [27]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")

df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
Notes                  object
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [28]:
df["Age"].fillna(df["Age"].median())
df["Score"].fillna(df["Score"].mean())

0    95.5
1    92.0
2    88.0
3    92.5
4    92.0
Name: Score, dtype: float64

In [ ]:
df["Signup Date"].fillna(df["Signup Date"].min())

In [29]:
df["Signup Date"].fillna("No Notes yet")

0    2022-01-01 00:00:00
1           No Notes yet
2           No Notes yet
3           No Notes yet
4           No Notes yet
Name: Signup Date, dtype: object

In [13]:
df["Name"].fillna("Unknown")

0      Alice
1        Bob
2    Charlie
3      David
4    Unknown
Name: Name, dtype: object

### 🤓 6. Cleaned Data Review

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      object
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 292.0+ bytes

In [30]:
df.describe(include="all")

         Name        Age          Signup Date      Score Notes
count       4   3.000000                    1   3.000000     3
unique      4        NaN                  NaN        NaN     2
top     Alice        NaN                  NaN        NaN
freq        1        NaN                  NaN        NaN     2
mean      NaN  33.333333  2022-01-01 00:00:00  92.000000   NaN
min       NaN  25.000000  2022-01-01 00:00:00  88.000000   NaN
25%       NaN  30.000000  2022-01-01 00:00:00  90.250000   NaN
50%       NaN  35.000000  2022-01-01 00:00:00  92.500000   NaN
75%       NaN  37.500000  2022-01-01 00:00:00  94.000000   NaN
max       NaN  40.000000  2022-01-01 00:00:00  95.500000   NaN
std       NaN   7.637626                  NaN   3.774917   NaN

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [9]:

df = pd.read_csv("../../data/survey.csv")
df

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S10115,22,Female,History,3.75,NaN,NaN,01-Nov-2025,Yes,NaN,$50k-$75k,0,1,NaN,Go,NaN
116,S10116,18,Non-binary,Data Science,NaN,12.5,NaN,09/28/2025,Yes,NaN,>$100k,NaN,Yes,75%,JavaScript,Love the course.
117,S10117,NaN,NaN,Biology,3.2,0,NaN,2025-10-31,No,2028,<$25k,NaN,1,NaN,NaN,NaN
118,S10118,22,Non-binary,History,5.1,ten,five,09/05/2025,NaN,2028,<$25k,-5,Yes,62%,Rust,NaN
119,S10119,22,NaN,NaN,NaN,NaN,five,NaN,N,twenty28,$50k-$75k,NaN,NaN,NaN,NaN,Too much homework.

In [7]:
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
student_id               0
age                     33
gender                  23
major                   10
gpa                     44
study_hours_per_week    42
satisfaction_1_5        46
survey_date             32
dorm_resident           33
expected_grad_year      33
income_range            21
commute_minutes         53
clubs_member            25
attendance_rate         79
favorite_language       19
comments                52
dtype: int64

In [10]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["gpa"] = pd.to_numeric(df["gpa"], errors="coerce")
df["study_hours_per_week"] = pd.to_numeric(df["study_hours_per_week"], errors="coerce")
df["satisfaction_1_5"] = pd.to_numeric(df["satisfaction_1_5"], errors="coerce")
df["commute_minutes"] = pd.to_numeric(df["commute_minutes"], errors="coerce")
df["attendance_rate"] = pd.to_numeric(df["attendance_rate"].str.replace("%", ""), errors="coerce")
df["survey_date"] = pd.to_datetime(df["survey_date"], errors="coerce")

C:\Users\shara\AppData\Local\Temp\ipykernel_29604\3739426688.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["survey_date"] = pd.to_datetime(df["survey_date"], errors="coerce")

In [11]:
df["age"] = df["age"].fillna(df["age"].median())
df["gpa"] = df["gpa"].fillna(df["gpa"].median())
df["study_hours_per_week"] = df["study_hours_per_week"].fillna(df["study_hours_per_week"].median())
df["commute_minutes"] = df["commute_minutes"].fillna(df["commute_minutes"].median())
df["gender"] = df["gender"].fillna("Unknown")
df["major"] = df["major"].fillna("Unknown")
df = df.dropna(subset=["survey_date"])

In [ ]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 6 to 118
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            61 non-null     object
 1   age                   61 non-null     float64
 2   gender                61 non-null     object
 3   major                 61 non-null     object
 4   gpa                   61 non-null     float64
 5   study_hours_per_week  61 non-null     float64
 6   satisfaction_1_5      26 non-null     float64
 7   survey_date           61 non-null     datetime64[ns]
 8   dorm_resident         43 non-null     object
 9   expected_grad_year    44 non-null     object
 10  income_range          50 non-null     object
 11  commute_minutes       61 non-null     float64
 12  clubs_member          49 non-null     object
 13  attendance_rate       25 non-null     float64
 14  favorite_language     52 non-null     object
 15  comments              31 non-null     object
dtypes: datetime64[ns](1), float64(6), object(9)
memory usage: 8.1+ KB
None
            age        gpa  study_hours_per_week  satisfaction_1_5  \
count  61.00000  61.000000             61.000000         26.000000
mean   21.00000   3.960492             11.352459          2.653846
min    18.00000   2.350000             -3.000000          1.000000
25%    19.00000   3.750000             12.500000          2.000000
50%    21.00000   3.750000             12.500000          2.500000
75%    22.00000   3.750000             12.500000          3.000000
max    25.00000   5.100000             28.000000          5.000000
std     1.95789   0.572426              7.101845          1.164210

                         survey_date  commute_minutes  attendance_rate
count                             61        61.000000        25.000000
mean   2025-10-20 21:14:45.245901568         5.442623        94.920000
min              2025-09-02 00:00:00        -5.000000        62.000000
25%              2025-10-02 00:00:00         0.000000        89.000000
50%              2025-10-28 00:00:00         0.000000       105.000000
75%              2025-11-08 00:00:00         0.000000       105.000000
max              2025-11-30 00:00:00        75.000000       105.000000
std                              NaN        16.279358        14.183089

In [13]:
df

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
6,S10006,21.0,Prefer not to say,Business,3.75,12.5,2.0,2025-09-07,N,2028,NaN,0.0,FALSE,NaN,SQL,Need more examples.
8,S10008,21.0,Male,History,3.75,12.5,3.0,2025-10-18,Yes,2026,>$100k,-5.0,TRUE,NaN,Go,Love the course.
9,S10009,18.0,Female,Unknown,3.88,12.5,2.0,2025-11-08,N,twenty28,>$100k,0.0,1,NaN,JavaScript,Too much homework.
10,S10010,21.0,Non-binary,CS,3.75,12.5,4.0,2025-09-09,Y,2029,>$100k,28.0,FALSE,74.0,Python,NaN
11,S10011,18.0,Non-binary,Data Science,3.75,12.5,4.0,2025-11-09,No,twenty28,$25k-$50k,0.0,No,NaN,C++,Love the course.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,S10114,21.0,Non-binary,CS,3.75,12.5,NaN,2025-11-08,Yes,NaN,Prefer not to say,0.0,0,105.0,JavaScript,Too much homework.
115,S10115,22.0,Female,History,3.75,12.5,NaN,2025-11-01,Yes,NaN,$50k-$75k,0.0,1,NaN,Go,NaN
116,S10116,18.0,Non-binary,Data Science,3.75,12.5,NaN,2025-09-28,Yes,NaN,>$100k,0.0,Yes,75.0,JavaScript,Love the course.
117,S10117,21.0,Unknown,Biology,3.20,0.0,NaN,2025-10-31,No,2028,<$25k,0.0,1,NaN,NaN,NaN
118,S10118,22.0,Non-binary,History,5.10,12.5,NaN,2025-09-05,NaN,2028,<$25k,-5.0,Yes,62.0,Rust,NaN

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |