# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

### 📥 1. Load the Dataset

In [4]:
import pandas as pd

df = pd.read_csv("../../data/students.csv")
df.head()

    first_name last_name  math_score  science_score
0      Melanie     Baker          60             94
1       Joshua     Adams          61            100
2        James     Cohen          61             66
3         Adam     Adams          61             70
4  Christopher     Brown          62             64

### 🔢 2. Sorting Data

In [5]:
# Sort by math_score
df.sort_values(by="math_score")

     first_name  last_name  math_score  science_score
0       Melanie      Baker          60             94
1        Joshua      Adams          61            100
2         James      Cohen          61             66
3          Adam      Adams          61             70
4   Christopher      Brown          62             64
5       Anthony    Hawkins          62             74
6       Michael   Valencia          65             91
7         Debra    Cameron          65             84
8     Christine      Hicks          65             80
9       Anthony       Gray          65             74
10        Maria     Bright          66             74
11      Barbara   Williams          66             74
12  Christopher     Daniel          66             64
13       Joshua       Rice          67             80
14        Angel      Clark          67             78
15     Patricia    Jackson          68             72
16       Teresa      Hurst          69             77
17    Cassandra     Wright          70             75
18        Helen       Hahn          72             82
19     Nicholas       Ross          73            100
20          Amy    Parsons          73             77
21        Susan       Rios          74             64
22        Erica      Lynch          74             96
23      Jeffrey      Perez          74             89
24         Jill       Wong          75             83
25        Keith  Henderson          76             77
26      Jeffrey     Zuniga          77             99
27        Colin      Ellis          77             70
28       Amanda   Richards          77             84
29       Andrea   Robinson          81             95
30      Jessica      Baker          81             89
31        Janet  Rodriguez          82             62
32      Brandon     Burton          82             80
33      Cynthia     Maddox          84             73
34     Michelle      Davis          84             63
35         Eric    Edwards          86             77
36      William     Bowman          87             65
37      Lindsay    Hoffman          87             70
38      Matthew     Foster          88             98
39        Jesse      James          89             73
40      Bridget    Johnson          92            100
41        Craig    Ferrell          94             96
42      Matthew     Walter          94             73
43       Robert     Martin          94             62
44        Linda      Clark          95             83
45      Jeffery       Mayo          97             78
46  Christopher      Rocha          97            100
47         Lisa    Stewart          98             83
48       Jeremy     Conner          98             85
49     Danielle       Wood         100             95

In [6]:
# Sort by science_score descending
df.sort_values(by="science_score", ascending=False)

     first_name  last_name  math_score  science_score
1        Joshua      Adams          61            100
19     Nicholas       Ross          73            100
40      Bridget    Johnson          92            100
46  Christopher      Rocha          97            100
26      Jeffrey     Zuniga          77             99
38      Matthew     Foster          88             98
41        Craig    Ferrell          94             96
22        Erica      Lynch          74             96
29       Andrea   Robinson          81             95
49     Danielle       Wood         100             95
0       Melanie      Baker          60             94
6       Michael   Valencia          65             91
23      Jeffrey      Perez          74             89
30      Jessica      Baker          81             89
48       Jeremy     Conner          98             85
7         Debra    Cameron          65             84
28       Amanda   Richards          77             84
44        Linda      Clark          95             83
47         Lisa    Stewart          98             83
24         Jill       Wong          75             83
18        Helen       Hahn          72             82
32      Brandon     Burton          82             80
13       Joshua       Rice          67             80
8     Christine      Hicks          65             80
45      Jeffery       Mayo          97             78
14        Angel      Clark          67             78
25        Keith  Henderson          76             77
20          Amy    Parsons          73             77
16       Teresa      Hurst          69             77
35         Eric    Edwards          86             77
17    Cassandra     Wright          70             75
5       Anthony    Hawkins          62             74
11      Barbara   Williams          66             74
10        Maria     Bright          66             74
9       Anthony       Gray          65             74
39        Jesse      James          89             73
42      Matthew     Walter          94             73
33      Cynthia     Maddox          84             73
15     Patricia    Jackson          68             72
37      Lindsay    Hoffman          87             70
27        Colin      Ellis          77             70
3          Adam      Adams          61             70
2         James      Cohen          61             66
36      William     Bowman          87             65
12  Christopher     Daniel          66             64
4   Christopher      Brown          62             64
21        Susan       Rios          74             64
34     Michelle      Davis          84             63
31        Janet  Rodriguez          82             62
43       Robert     Martin          94             62

In [7]:
# Sort by multiple columns
df.sort_values(by=["science_score", "math_score"], ascending=[False, True])

     first_name  last_name  math_score  science_score
1        Joshua      Adams          61            100
19     Nicholas       Ross          73            100
40      Bridget    Johnson          92            100
46  Christopher      Rocha          97            100
26      Jeffrey     Zuniga          77             99
38      Matthew     Foster          88             98
22        Erica      Lynch          74             96
41        Craig    Ferrell          94             96
29       Andrea   Robinson          81             95
49     Danielle       Wood         100             95
0       Melanie      Baker          60             94
6       Michael   Valencia          65             91
23      Jeffrey      Perez          74             89
30      Jessica      Baker          81             89
48       Jeremy     Conner          98             85
7         Debra    Cameron          65             84
28       Amanda   Richards          77             84
24         Jill       Wong          75             83
44        Linda      Clark          95             83
47         Lisa    Stewart          98             83
18        Helen       Hahn          72             82
8     Christine      Hicks          65             80
13       Joshua       Rice          67             80
32      Brandon     Burton          82             80
14        Angel      Clark          67             78
45      Jeffery       Mayo          97             78
16       Teresa      Hurst          69             77
20          Amy    Parsons          73             77
25        Keith  Henderson          76             77
35         Eric    Edwards          86             77
17    Cassandra     Wright          70             75
5       Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
10        Maria     Bright          66             74
11      Barbara   Williams          66             74
33      Cynthia     Maddox          84             73
39        Jesse      James          89             73
42      Matthew     Walter          94             73
15     Patricia    Jackson          68             72
3          Adam      Adams          61             70
27        Colin      Ellis          77             70
37      Lindsay    Hoffman          87             70
2         James      Cohen          61             66
36      William     Bowman          87             65
4   Christopher      Brown          62             64
12  Christopher     Daniel          66             64
21        Susan       Rios          74             64
34     Michelle      Davis          84             63
31        Janet  Rodriguez          82             62
43       Robert     Martin          94             62

### 🧪 3. Filtering with Conditions

In [8]:
# Who scored at least 90 in math?
df[df["math_score"] >= 90]

     first_name last_name  math_score  science_score
40      Bridget   Johnson          92            100
41        Craig   Ferrell          94             96
42      Matthew    Walter          94             73
43       Robert    Martin          94             62
44        Linda     Clark          95             83
45      Jeffery      Mayo          97             78
46  Christopher     Rocha          97            100
47         Lisa   Stewart          98             83
48       Jeremy    Conner          98             85
49     Danielle      Wood         100             95

In [9]:
# Who scored less than 70 in either subject?
df[(df["math_score"] < 70) | (df["science_score"] < 70)]

     first_name  last_name  math_score  science_score
0       Melanie      Baker          60             94
1        Joshua      Adams          61            100
2         James      Cohen          61             66
3          Adam      Adams          61             70
4   Christopher      Brown          62             64
5       Anthony    Hawkins          62             74
6       Michael   Valencia          65             91
7         Debra    Cameron          65             84
8     Christine      Hicks          65             80
9       Anthony       Gray          65             74
10        Maria     Bright          66             74
11      Barbara   Williams          66             74
12  Christopher     Daniel          66             64
13       Joshua       Rice          67             80
14        Angel      Clark          67             78
15     Patricia    Jackson          68             72
16       Teresa      Hurst          69             77
21        Susan       Rios          74             64
31        Janet  Rodriguez          82             62
34     Michelle      Davis          84             63
36      William     Bowman          87             65
43       Robert     Martin          94             62

### 🔗 4. Combining Filters

In [10]:
# Students with B+ or higher in both
df[(df["math_score"] >= 87) & (df["science_score"] >= 87)]

     first_name last_name  math_score  science_score
38      Matthew    Foster          88             98
40      Bridget   Johnson          92            100
41        Craig   Ferrell          94             96
46  Christopher     Rocha          97            100
49     Danielle      Wood         100             95

### 🧾 5. Using `.query()` for Readability

In [11]:
# Same query using .query()
df.query("math_score >= 87 and science_score >= 87")

     first_name last_name  math_score  science_score
38      Matthew    Foster          88             98
40      Bridget   Johnson          92            100
41        Craig   Ferrell          94             96
46  Christopher     Rocha          97            100
49     Danielle      Wood         100             95

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [13]:
df.sort_values("first_name")

     first_name  last_name  math_score  science_score
3          Adam      Adams          61             70
28       Amanda   Richards          77             84
20          Amy    Parsons          73             77
29       Andrea   Robinson          81             95
14        Angel      Clark          67             78
5       Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
11      Barbara   Williams          66             74
32      Brandon     Burton          82             80
40      Bridget    Johnson          92            100
17    Cassandra     Wright          70             75
8     Christine      Hicks          65             80
46  Christopher      Rocha          97            100
12  Christopher     Daniel          66             64
4   Christopher      Brown          62             64
27        Colin      Ellis          77             70
41        Craig    Ferrell          94             96
33      Cynthia     Maddox          84             73
49     Danielle       Wood         100             95
7         Debra    Cameron          65             84
35         Eric    Edwards          86             77
22        Erica      Lynch          74             96
18        Helen       Hahn          72             82
2         James      Cohen          61             66
31        Janet  Rodriguez          82             62
45      Jeffery       Mayo          97             78
23      Jeffrey      Perez          74             89
26      Jeffrey     Zuniga          77             99
48       Jeremy     Conner          98             85
39        Jesse      James          89             73
30      Jessica      Baker          81             89
24         Jill       Wong          75             83
13       Joshua       Rice          67             80
1        Joshua      Adams          61            100
25        Keith  Henderson          76             77
44        Linda      Clark          95             83
37      Lindsay    Hoffman          87             70
47         Lisa    Stewart          98             83
10        Maria     Bright          66             74
42      Matthew     Walter          94             73
38      Matthew     Foster          88             98
0       Melanie      Baker          60             94
6       Michael   Valencia          65             91
34     Michelle      Davis          84             63
19     Nicholas       Ross          73            100
15     Patricia    Jackson          68             72
43       Robert     Martin          94             62
21        Susan       Rios          74             64
16       Teresa      Hurst          69             77
36      William     Bowman          87             65

In [14]:
df[df["math_score"] == df["science_score"]]

Empty DataFrame
Columns: [first_name, last_name, math_score, science_score]
Index: []

In [15]:
df.query("math_score > 95 or science_score > 95")

     first_name last_name  math_score  science_score
1        Joshua     Adams          61            100
19     Nicholas      Ross          73            100
22        Erica     Lynch          74             96
26      Jeffrey    Zuniga          77             99
38      Matthew    Foster          88             98
40      Bridget   Johnson          92            100
41        Craig   Ferrell          94             96
45      Jeffery      Mayo          97             78
46  Christopher     Rocha          97            100
47         Lisa   Stewart          98             83
48       Jeremy    Conner          98             85
49     Danielle      Wood         100             95

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

In [28]:
survey = pd.read_csv(r"../../Lessons/07-Sorting_and_Filtering/data/survey.csv")

In [32]:
survey = survey.sort_values(by="survey_date", ascending=False)
print(survey)

    student_id     age             gender       major   gpa  \
78      S10078      24                NaN  Undeclared   NaN
58      S10058      21  Prefer not to say          CS   NaN
38      S10038     NaN  Prefer not to say    Business   5.1
41      S10041  twenty  Prefer not to say     History   5.1
96      S10096      24                NaN        Math   NaN
..         ...     ...                ...         ...   ...
102     S10102      19             Female    Business   NaN
105     S10105      25                NaN     History   NaN
106     S10106      20         Non-binary    Business   5.1
111     S10111      23             Female  Undeclared  3.75
119     S10119      22                NaN         NaN   NaN

    study_hours_per_week satisfaction_1_5  survey_date dorm_resident  \
78                  12.5              NaN  29-Sep-2025             N
58                    20                5  29-Nov-2025             Y
38                   NaN              NaN  28-Sep-2025           NaN
41                  12.5                2  25-Sep-2025             N
96                   NaN              NaN  24-Nov-2025           NaN
..                   ...              ...          ...           ...
102                   -3              NaN          NaN            No
105                  ten              NaN          NaN             Y
106                    0                3          NaN           Yes
111                 12.5              NaN          NaN           Yes
119                  NaN             five          NaN             N

    expected_grad_year       income_range commute_minutes clubs_member  \
78                2027             >$100k             NaN           No
58                2030          $50k-$75k               1            0
38                 NaN          $50k-$75k             NaN         TRUE
41                 NaN          $25k-$50k              38          Yes
96            twenty28             >$100k             NaN            0
..                 ...                ...             ...          ...
102               2028                NaN               0         TRUE
105               2026          $25k-$50k               0            0
106               2027          $50k-$75k              -5        FALSE
111           twenty28  Prefer not to say             NaN            0
119           twenty28          $50k-$75k             NaN          NaN

    attendance_rate favorite_language             comments
78              NaN                Go                  NaN
58             105%              Rust                  NaN
38              NaN        JavaScript                  NaN
41             105%            Python       Lectures are 🔥
96              NaN               NaN       Lectures are 🔥
..              ...               ...                  ...
102             NaN               C++                  NaN
105            105%        JavaScript  Need more examples.
106             NaN               NaN       Lectures are 🔥
111             NaN            Python                  NaN
119             NaN               NaN   Too much homework.

[120 rows x 16 columns]

In [35]:
# Remove rows where ANY column is null
survey_clean = survey.replace("N/A", pd.NA).dropna()
print(survey_clean)

Empty DataFrame
Columns: [student_id, age, gender, major, gpa, study_hours_per_week, satisfaction_1_5, survey_date, dorm_resident, expected_grad_year, income_range, commute_minutes, clubs_member, attendance_rate, favorite_language, comments]
Index: []

In [37]:
survey.query("gender == 'Female'")

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN
13,S10013,25,Female,Data Science,5.1,-3,2,2025-13-40,Yes,2026,<$25k,NaN,1,NaN,NaN,Need more examples.
14,S10014,18,Female,Undeclared,NaN,NaN,5,2025-13-40,No,twenty28,$25k-$50k,NaN,No,80%,Python,Love the course.
89,S10089,23,Female,Undeclared,NaN,7,NaN,2025-13-40,No,NaN,NaN,NaN,TRUE,NaN,NaN,Lectures are 🔥
85,S10085,21,Female,Math,5.1,NaN,five,2025-13-40,Yes,2026,Prefer not to say,NaN,1,105%,Java,Too much homework.
53,S10053,24,Female,Undeclared,3.75,0,NaN,2025-13-40,N,twenty28,<$25k,15,FALSE,105%,NaN,NaN
59,S10059,23,Female,Biology,3.75,NaN,2,2025-13-40,Y,NaN,NaN,56,NaN,NaN,Java,NaN
72,S10072,NaN,Female,Undeclared,5.1,-3,1,2025-13-40,No,NaN,<$25k,NaN,NaN,NaN,Go,Lectures are 🔥
61,S10061,20,Female,Undeclared,5.1,20,2,2025-10-21,NaN,2027,$75k-$100k,NaN,1,NaN,Go,NaN
103,S10103,22,Female,Math,3.75,20,five,2025-10-07,NaN,2029,Prefer not to say,NaN,Yes,105%,Rust,NaN
98,S10098,19,Female,Business,"4,0",NaN,NaN,18-Oct-2025,NaN,2027,>$100k,15,1,75%,Rust,Lectures are 🔥
82,S10082,NaN,Female,Computer Science,NaN,-3,five,11/18/2025,NaN,NaN,$50k-$75k,0,NaN,NaN,Python,NaN
101,S10101,20,Female,CS,"4,0",20,NaN,11/10/2025,Yes,2027,<$25k,0,0,105%,SQL,NaN
9,S10009,18,Female,NaN,3.88,NaN,2,11/08/2025,N,twenty28,>$100k,NaN,1,NaN,JavaScript,Too much homework.
22,S10022,NaN,Female,History,3.75,0,1,10/31/2025,N,twenty28,$50k-$75k,45 min,No,NaN,JavaScript,Love the course.
19,S10019,NaN,Female,Business,3.75,12.5,five,02-Nov-2025,Y,2027,Prefer not to say,NaN,TRUE,NaN,Go,Love the course.
115,S10115,22,Female,History,3.75,NaN,NaN,01-Nov-2025,Yes,NaN,$50k-$75k,0,1,NaN,Go,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
42,S10042,22,Female,CS,2.03,12.5,NaN,NaN,NaN,2028,<$25k,-5,FALSE,NaN,C++,NaN
92,S10092,24,Female,Data Science,NaN,-3,five,NaN,Yes,2026,$75k-$100k,60,1,NaN,Rust,Lectures are 🔥
99,S10099,18,Female,CS,"4,0",12.5,5,NaN,N,NaN,Prefer not to say,45 min,FALSE,NaN,C++,Too much homework.
102,S10102,19,Female,Business,NaN,-3,NaN,NaN,No,2028,NaN,0,TRUE,NaN,C++,NaN
111,S10111,23,Female,Undeclared,3.75,12.5,NaN,NaN,Yes,twenty28,Prefer not to say,NaN,0,NaN,Python,NaN

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |