# 🧪 Pandas Wrangle Lab: Clean & Explore a Real Dataset

## 🔹 LEARNING GOALS:
- Practice loading, cleaning, and exploring real-world data
- Apply column creation, renaming, sorting, and filtering
- Use `.info()`, `.describe()`, and `.query()` fluently

### 📥 1. Load the Dataset

In [23]:
import pandas as pd
df = pd.read_csv("../../data/students.csv")
df.head()

    first_name last_name  math_score  science_score
0      Melanie     Baker          60             94
1       Joshua     Adams          61            100
2        James     Cohen          61             66
3         Adam     Adams          61             70
4  Christopher     Brown          62             64

### 🔎 2. Inspect and Audit the Data

In [2]:
# Basic overview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     50 non-null     object
 1   last_name      50 non-null     object
 2   math_score     50 non-null     int64
 3   science_score  50 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.7+ KB

In [3]:
# Summary stats
df.describe()

       math_score  science_score
count    50.00000      50.000000
mean     77.56000      80.240000
std      12.17753      11.659384
min      60.00000      62.000000
25%      66.25000      73.000000
50%      75.50000      78.000000
75%      87.00000      89.000000
max     100.00000     100.000000

### 🧼 3. Clean Missing or Invalid Data

In [4]:
# Check for missing values
df.isnull().sum()

first_name       0
last_name        0
math_score       0
science_score    0
dtype: int64

In [7]:
# Drop rows with missing names
df.dropna(subset=["first_name", "last_name"], inplace=True)

# Fill any missing scores with column average
df["math_score"].fillna(df["math_score"].mean(), inplace=True)
df["science_score"].fillna(df["science_score"].mean(), inplace=True)

C:\Users\shara\AppData\Local\Temp\ipykernel_16248\210016614.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["math_score"].fillna(df["math_score"].mean(), inplace=True)
C:\Users\shara\AppData\Local\Temp\ipykernel_16248\210016614.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["science_score"].fillna(df["science_score"].mean(), inplace=True)

### 🧠 4. Feature Engineering (New Columns)

In [24]:
# Add average and grade
df["average_score"] = (df["math_score"] + df["science_score"]) / 2

def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"

df["grade"] = df["average_score"].apply(grade)
df.head()

    first_name last_name  math_score  science_score  average_score grade
0      Melanie     Baker          60             94           77.0     C
1       Joshua     Adams          61            100           80.5     B
2        James     Cohen          61             66           63.5     D
3         Adam     Adams          61             70           65.5     D
4  Christopher     Brown          62             64           63.0     D

### 🔽 5. Sorting and Filtering

In [25]:
# Top performers
df[df["average_score"] > 90].sort_values(by="average_score", ascending=False).head()

     first_name last_name  math_score  science_score  average_score grade
46  Christopher     Rocha          97            100           98.5     A
49     Danielle      Wood         100             95           97.5     A
40      Bridget   Johnson          92            100           96.0     A
41        Craig   Ferrell          94             96           95.0     A
38      Matthew    Foster          88             98           93.0     A

### 📊 6. Group and Describe by Grade

In [26]:
# How many of each grade?
df["grade"].value_counts()

grade
C    22
B    14
D     7
A     7
Name: count, dtype: int64

In [27]:
# Average scores per grade group
df.groupby("grade")[["math_score", "science_score", "average_score"]].mean()
print(df)

     first_name  last_name  math_score  science_score  average_score grade
0       Melanie      Baker          60             94           77.0     C
1        Joshua      Adams          61            100           80.5     B
2         James      Cohen          61             66           63.5     D
3          Adam      Adams          61             70           65.5     D
4   Christopher      Brown          62             64           63.0     D
5       Anthony    Hawkins          62             74           68.0     D
6       Michael   Valencia          65             91           78.0     C
7         Debra    Cameron          65             84           74.5     C
8     Christine      Hicks          65             80           72.5     C
9       Anthony       Gray          65             74           69.5     D
10        Maria     Bright          66             74           70.0     C
11      Barbara   Williams          66             74           70.0     C
12  Christopher     Daniel          66             64           65.0     D
13       Joshua       Rice          67             80           73.5     C
14        Angel      Clark          67             78           72.5     C
15     Patricia    Jackson          68             72           70.0     C
16       Teresa      Hurst          69             77           73.0     C
17    Cassandra     Wright          70             75           72.5     C
18        Helen       Hahn          72             82           77.0     C
19     Nicholas       Ross          73            100           86.5     B
20          Amy    Parsons          73             77           75.0     C
21        Susan       Rios          74             64           69.0     D
22        Erica      Lynch          74             96           85.0     B
23      Jeffrey      Perez          74             89           81.5     B
24         Jill       Wong          75             83           79.0     C
25        Keith  Henderson          76             77           76.5     C
26      Jeffrey     Zuniga          77             99           88.0     B
27        Colin      Ellis          77             70           73.5     C
28       Amanda   Richards          77             84           80.5     B
29       Andrea   Robinson          81             95           88.0     B
30      Jessica      Baker          81             89           85.0     B
31        Janet  Rodriguez          82             62           72.0     C
32      Brandon     Burton          82             80           81.0     B
33      Cynthia     Maddox          84             73           78.5     C
34     Michelle      Davis          84             63           73.5     C
35         Eric    Edwards          86             77           81.5     B
36      William     Bowman          87             65           76.0     C
37      Lindsay    Hoffman          87             70           78.5     C
38      Matthew     Foster          88             98           93.0     A
39        Jesse      James          89             73           81.0     B
40      Bridget    Johnson          92            100           96.0     A
41        Craig    Ferrell          94             96           95.0     A
42      Matthew     Walter          94             73           83.5     B
43       Robert     Martin          94             62           78.0     C
44        Linda      Clark          95             83           89.0     B
45      Jeffery       Mayo          97             78           87.5     B
46  Christopher      Rocha          97            100           98.5     A
47         Lisa    Stewart          98             83           90.5     A
48       Jeremy     Conner          98             85           91.5     A
49     Danielle       Wood         100             95           97.5     A

### 💾 7. Save the Cleaned Dataset

In [28]:
df.to_csv("student_scores_cleaned.csv", index=False)

### 🧠 Challenge Task

> Your turn! Filter out students who got a D, sort by last name, and export to a new file:
- Only include columns: `first_name`, `last_name`, `grade`
- Save it as `"d_students.csv"`

In [30]:
filtered = df.query("grade != 'D'")
filtered = filtered.sort_values("last_name")
filtered = filtered[["first_name", "last_name", "grade"]]
filtered.to_csv("d_students.csv", index=False)

In [31]:
print(filtered)

     first_name  last_name grade
1        Joshua      Adams     B
0       Melanie      Baker     C
30      Jessica      Baker     B
36      William     Bowman     C
10        Maria     Bright     C
32      Brandon     Burton     B
7         Debra    Cameron     C
44        Linda      Clark     B
14        Angel      Clark     C
48       Jeremy     Conner     A
34     Michelle      Davis     C
35         Eric    Edwards     B
27        Colin      Ellis     C
41        Craig    Ferrell     A
38      Matthew     Foster     A
18        Helen       Hahn     C
25        Keith  Henderson     C
8     Christine      Hicks     C
37      Lindsay    Hoffman     C
16       Teresa      Hurst     C
15     Patricia    Jackson     C
39        Jesse      James     B
40      Bridget    Johnson     A
22        Erica      Lynch     B
33      Cynthia     Maddox     C
43       Robert     Martin     C
45      Jeffery       Mayo     B
20          Amy    Parsons     C
23      Jeffrey      Perez     B
13       Joshua       Rice     C
28       Amanda   Richards     B
29       Andrea   Robinson     B
46  Christopher      Rocha     A
31        Janet  Rodriguez     C
19     Nicholas       Ross     B
47         Lisa    Stewart     A
6       Michael   Valencia     C
42      Matthew     Walter     B
11      Barbara   Williams     C
24         Jill       Wong     C
49     Danielle       Wood     A
17    Cassandra     Wright     C
26      Jeffrey     Zuniga     B

### 📝 Summary

This lab gave you hands-on experience with:
- Cleaning nulls and type mismatches
- Creating new columns
- Filtering and sorting real data
- Grouping and summarizing by categorical features

Your data wrangling toolbox is now ready for real-world messiness. 🧹🛠️